### ISSUE TITLE
Microsoft.Azure.WebJobs.Extensions.EventGrid.EventGridEvent is obsolete, but new version doesn't work with EventGridTrigger

### ISSUE THREAD

**Issue by gdodd1977** [Azure/azure-functions-eventgrid-extension#50]
I'm attempting to use EventGridTrigger with EventGridEvent, but the EventGridEvent referenced in the docs is marked obsolete. It says to use the one from Microsoft.Azure.EventGrid.Models. But when I do that, I get the following error:
 Microsoft.Azure.WebJobs.Extensions.EventGrid: Can't bind EventGridTriggerAttribute to type 'Microsoft.Azure.EventGrid.Models.EventGridEvent'.

Is there a new EventGridTrigger in a different package that works with this EventGridEvent?

I'm using functions v1 and running it as .net 461.

**Comment by jeffhollan** [comment]
This is an understandable confusion.  Here's the answer and then some history.  In short with v1 functions and event grid the best option is to bind to `JObject` as the v1 runtime comes with its own version of `EventGridEvent` which is different from `Microsoft.Azure.EventGrid.Models.EventGridEvent`.  Once inside the execution you should be able to convert the `JObject` to an `EventGrid.Models.EventGridEvent` I believe - but you will likely need to reference via the full namespace path as will be two instances of `EventGridEvent` classes.

The history is because when we first launched the Event Grid trigger there was no Event Grid SDK so we built our own model. A few months later they launched the event grid SDK. However one of the downsides of the v1 runtime is we can't do breaking changes without breaking existing apps as extensions ship with the host.  So we decided **not** to update v1 to support the EventGrid.Models.EventGrid as it would break previously bulit apps.  For v2 though we do have flexibility to version so v2 apps will use the SDK.

It shouldn't have any negative effects - it's just how the message gets serialized into your function. The only downside as mentioned is if you do try to use the EventGrid SDK you may have two `EventGridEvent` classes so you will need to specify exactly which one you intend -- and the EventGrid SDK one can't be used as the trigger type.

Hopefully that makes some sense

**Comment by gdodd1977** [comment]
Ok. That makes sense. I will give it a shot with the JObject. Thanks!
